### ISSUE TITLE
Drawing nodes at variable dimensions

### ISSUE THREAD

**Issue by mbodini** [abrozzi/microbio#1]
Dear Alessandro,

Firstly I want to thank you for this powerful tool that simplifies our everyday work.
I am trying to use `add.nex.features` function to draw the nodes at different dimensions but when I put the nexus file obtained in Splits Tree I get the following error:
`Error parsing file: line 233: w='1': number expected`

Do you know the reason for this error? Could you please help me in solving this issue?

Thank you very much,

Margherita

**Comment by abrozzi** [comment]
Hi Margherita,
I added the option to pass "w" and "h" that specifies the width and height of each point as vectors. If the vector is of length 1 all the nodes will have the same width and height.

HTH
-A
