### ISSUE TITLE
get.nexus.tips() splits at spaces - perhaps warn other users?

### ISSUE THREAD

**Issue by HedvigS** [abrozzi/microbio#2]
It took me a while to figure out what was going wrong when I was running custom_nexus(). It kept telling me that my tips and taxa weren't of the same length, but I knew that they were. Then I realised that get.nexus.tips() splits at spaces, and I have spaces in my tips. I've replaced those with underscores now, but for future users it might be worth pointing that out somewhere?

SplitsTree doesn't like single quotes, but is actually okay with spaces in label names so others might have a similar set up.

Thanks for a great package by the way, once I got over this bump it works great :)! I work in linguistics and like using SplitsTree to visualise distances in my data. I would highly support you putting this package on CRAN and perhaps changing it to "custom_SplitsTree_nexus" or something like that. I think more people who aren't in microbiology would use this :D

**Comment by HedvigS** [comment]
Results :)
![sahul_weighted_controlled_colored](https://user-images.githubusercontent.com/5327845/59746027-5853c200-92b9-11e9-9c7c-b3ccd316f9a0.png)
https://twitter.com/Laserhedvig/status/1141248446549991424

**Comment by abrozzi** [comment]
Hi Hedvig,
thanks a lot for your feedback.
That was actually a pilot project. I actually developed a more mature package called SplitsT*R*ee that also enables to import a network from SplitsTree into R to graph edges and nodes in a canonical R mode.
I  will be glad to share with you my work to give the package the worth shape for a CRAN package.
Bests,
-A

**Comment by HedvigS** [comment]
Cool!

Can I find this package somewhere already now?

**Comment by HedvigS** [comment]
I haven't had any trouble yet with the old custom.nexus() function so I'll be honest, I've found where the new functions are but I haven't switched over yet. But, thank you for your work nonetheless!!
