### ISSUE TITLE
The function read.breseq.gd give an empty file

### ISSUE THREAD

**Issue by loukesio** [abrozzi/microbio#4]
Thank you for posting an interesting function. 
I did try to apply it in my gd files and did not get any output. 
you can check this one https://1drv.ms/u/s!ArOzUuixE-mggYVXbvEg6idKSpB6Fg?e=HnQ8DI

thank you for your time

**Comment by abrozzi** [comment]
Hi loukesio,
yes there is in fact a missing part in the function body. My fault. I am going to correct it and provide an help page.
Thanks for spotting.

-A

**Comment by loukesio** [comment]
Dear Alessandro, 

You are welcome, reading these files is a total pain. First I transform them to GVF files then I concatenate them with the index.html to get the info I need. 

I am looking forward to your function though 

with best wishes, 
Loukas

**Comment by abrozzi** [comment]
Dear Loukas! 
```breseq``` output is complicated beyond its apparent table-like simplicity.
I opened an issue https://github.com/barricklab/breseq/issues/258#issue-798294612 to ask to list all possible tags.
Meanwhile they answer I've finished the body of the function which imports ```SNP``` lines allowing all possible tags.

**Comment by abrozzi** [comment]
Dear Loukas,

have look here:

https://github.com/barricklab/breseq/issues/258#issuecomment-771802194ù

I think it is solved.

-A

**Comment by loukesio** [comment]
Dear Alessandro, 

That sounds great. Thank you 

with best wishes, 
Loukas
